### ISSUE TITLE
Omitting direction, result: error

### ISSUE THREAD

**Issue by nesalkiN** [DSorlov/hasl-platform#12] opened 2019-04-16 16:20 UTC
Not defining direction:

> Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 379, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/sl/sensor.py", line 206, in update
    if (int(self._direction) == 0 or
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

direction: 0 works but the sensor will be named friendlyname_3.

**Comment by DSorlov** [comment] 2019-04-16 17:02
Was the problem with direction or naming?

I have uploaded a new file with a default value set for the direction so that does not need to be specified as written in the documentation. So that part should work. Will publish new version later this week but fix is checked in: https://github.com/DSorlov/ha-sensor-sl/commit/fe999b46553b02ef18b2949062cba0ecf1406398

**Comment by nesalkiN** [comment] 2019-04-16 17:03
When I used direction: 0 the name for the sensor was sensor.friendlyname_3.

**Comment by DSorlov** [comment] 2019-04-16 18:50
Strange; I cannot reproduce. Could you confirm this still errors when using 1.0.3?

**Comment by nesalkiN** [comment] 2019-04-16 19:01
Yes, The name is still sensor.friendlyname_3. I have removed "direction: 0". Replace "friendlyname" with your own. It could be as designed? :)

**Comment by nesalkiN** [comment] 2019-04-16 19:07
OT. I like the new updating time left. 

Could the real time be shown even for shorter time left? 
![Capture_Home_Assistant_-_Google_Chrome_2019-04-16_21-05-46_38734231](https://user-images.githubusercontent.com/4583709/56237129-8a636080-608b-11e9-8d4d-a6d4547ae7d0.png)
I would like to see 3 min (21:07). ;)

**Comment by DSorlov** [comment] 2019-04-18 12:17
About sensor naming I have created a separate issue to track that in #15

**Closed as completed by DSorlov** 2019-04-18 12:17 UTC
Labels: bug
