### ISSUE TITLE
HTTP error 907 after upgade to HA 2021.12.1

### ISSUE THREAD

**Issue by grobius** [DSorlov/hasl-platform#67] opened 2021-12-14 18:10 UTC
I get api_result: 'SLAPI_HTTP_Error 997: A HTTP error occured' on the integration after updating to HA 2021.12.1

Checked that API and key works

**Comment by DSorlov** [comment] 2021-12-14 18:19
Will look into this in a few days if noone else have the time. Need to upgrade my enviroments first to verify. Anything more detailed in the logs? Which hardware/software are you running on?

**Comment by grobius** [comment] 2021-12-15 09:26
Thx for your efforts!

Can't really find anything more than this warning:

2021-12-14 19:26:00 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sl_departure_sensor_9681_sl_integration (<class 'custom_components.hasl3.sensor.HASLDepartureSensor'>) implements device_state_attributes. Please report it to the custom component author.

_State attributes reports the following:_

unit_of_measurement: min
api_result: 'SLAPI_HTTP_Error 997: A HTTP error occured'
scan_interval: 360
refresh_enabled: true
icon: mdi:train
friendly_name: SL Departure Sensor 9681 (SL integration)

Im running on ODROID-N2+ Home Assistant Blue

**Comment by DSorlov** [comment] 2021-12-16 09:38
Hi! Still trying to verify this however I would recommend moving to HASLv3 instead of using this older version; if the error would involve fixing beyond simple ones it will not be completed HASL is nearing it's end of life (to be replaced by the more friendly HASLv3 instead and that one still seems to be working). HASLv3 is available in HACS also.

**Comment by DSorlov** [comment] 2021-12-16 15:39
Have not been able to reproduce this error either in HASLv3 or HASL. Could you paste your config to see if there is any data that is coming in specific to your install?

**Comment by lawi75** [comment] 2021-12-17 12:29
I have the same issue on HASLv3 API Beta 3 running on odroid (https://www.home-assistant.io/blue/). When I call the Trafik info API from a browser I get results back so no issue with my API key or station number

**Comment by DSorlov** [comment] 2021-12-17 12:35
Thanks @lawi75 for confirmation. Still trying to replicate in my end.

**Comment by grobius** [comment] 2021-12-17 15:06
Sorry, I got confused here. I realized it's HASLv3 I'm running. sorry for posting in wrong repo.

Seems lite it could be realted to that device_state_attributes -> extra_state_attributes name change seems to be implemented from 2021.12.x

**Comment by DSorlov** [comment] 2021-12-20 22:06
Ok! Thanks everyone! Have now identified the error, it will be updated in the coming days. 
Have opened a new issue in the correct location: https://github.com/hasl-sensor/integration/issues/18

**Closed as completed by DSorlov** 2021-12-20 22:06 UTC
Labels: investigating

**Comment by DSorlov** [comment] 2021-12-28 19:17
This have now been addressed in v3.0.0-beta.4 of HASLv3 that is available from HACS. Due to the breaking changes in Home Assistant this version will be terminated very soon, expected to be archived within week 1 of 2022. It also means that HACSv3 is the recommended and only supported version. Please try out the new version if you have not.  

Please see https://github.com/hasl-sensor/integration

**Comment by grobius** [comment] 2021-12-29 13:40
Thanks, everything working as expected in HASLv3 again
