### ISSUE TITLE
Departures are always empty

### ISSUE THREAD

**Issue by marcus13371337** [DSorlov/hasl-platform#50] opened 2019-11-30 23:38 UTC
Hi,

Great component, mucho cred!

However, it seems that the API-response might have been changed. Because I don't get any departures into my sensor. This is how it looks:
```
unit_of_measurement: min
refresh_enabled: 'on'
attribution: Stockholms Lokaltrafik
departures: []
deviations: []
last_refresh: '2019-12-01 00:29:24'
next_departure_minutes: '-'
next_departure_time: '-'
deviation_count: 0
friendly_name: Alvik
icon: 'mdi:bus'
```
Looking in https://github.com/DSorlov/hasl-platform/blob/hasl/custom_components/hasl/sensor.py line 392:
```
                    apidata = apidata['ResponseData']['TrafficTypes']
```
When looking in the response from the endpoint I have:
```
{
"StatusCode": 0,
"Message": null,
"ExecutionTime": 79,
"ResponseData": {
"LatestUpdate": "2019-12-01T00:27:06",
"DataAge": 24,
"Metros": [
{
"GroupOfLine": "tunnelbanans gröna linje",
"DisplayTime": "00:31",
"TransportMode": "METRO",
"LineNumber": "18",
"Destination": "Farsta strand",
"JourneyDirection": 2,
"StopAreaName": "Alvik",
"StopAreaNumber": 1201,
"StopPointNumber": 1202,
"StopPointDesignation": "4",
"TimeTabledDateTime": "2019-12-01T00:31:00",
"ExpectedDateTime": "2019-12-01T00:31:00",
"JourneyNumber": 10200,
"Deviations": null
...
```

Has SL updated their response schema?

**Comment by marcus13371337** [comment] 2019-11-30 23:40
Never mind, looked in the wrong API. However, the problem still exists

**Comment by DSorlov** [comment] 2019-11-30 23:43
How do your config look? At this time of day there might not be any departures in the next hour or so? All looks good here when trying a known-good config.

**Comment by marcus13371337** [comment] 2019-11-30 23:44
Looks like this:
```
  - platform: hasl
    ri4key: XX
    si2key: XX
    tl2key: XX
    sensors:
       - friendly_name: Alvik
         sensor_type: departures
         siteid: 9112
         direction: 0
         scan_interval: 60
       - friendly_name: Trafikstatus
         sensor_type: status
         scan_interval: 60
```

**Comment by marcus13371337** [comment] 2019-11-30 23:46
Should be stuff leaving, from the RI4 api just now:
```
{
"StatusCode": 0,
"Message": null,
"ExecutionTime": 75,
"ResponseData": {
"LatestUpdate": "2019-12-01T00:45:15",
"DataAge": 7,
"Metros": [
{
"GroupOfLine": "tunnelbanans gröna linje",
"DisplayTime": "Nu",
"TransportMode": "METRO",
"LineNumber": "18",
"Destination": "Farsta strand",
"JourneyDirection": 2,
"StopAreaName": "Alvik",
"StopAreaNumber": 1201,
"StopPointNumber": 1202,
"StopPointDesignation": "4",
"TimeTabledDateTime": "2019-12-01T00:46:00",
"ExpectedDateTime": "2019-12-01T00:46:00",
"JourneyNumber": 10201,
"Deviations": null
},
{
"GroupOfLine": "tunnelbanans gröna linje",
"DisplayTime": "1 min",
"TransportMode": "METRO",
"LineNumber": "17",
"Destination": "Åkeshov",
"JourneyDirection": 1,
"StopAreaName": "Alvik",
"StopAreaNumber": 1201,
"StopPointNumber": 1201,
"StopPointDesignation": "1",
"TimeTabledDateTime": "2019-12-01T00:46:30",
"ExpectedDateTime": "2019-12-01T00:46:30",
"JourneyNumber": 11010,
"Deviations": null
}
],
"Buses": [],
"Trains": [],
"Trams": [
{
"TransportMode": "TRAM",
"LineNumber": "22",
"Destination": "Solna station",
"JourneyDirection": 1,
"GroupOfLine": "Tvärbanan",
"StopAreaName": "Alvik",
"StopAreaNumber": 4525,
"StopPointNumber": 4525,
"StopPointDesignation": "5",
"TimeTabledDateTime": "2019-12-01T00:53:00",
"ExpectedDateTime": "2019-12-01T00:53:00",
"DisplayTime": "00:53",
"JourneyNumber": 12422,
"Deviations": null
}
],
"Ships": [],
"StopPointDeviations": [
{
"StopInfo": {
"StopAreaNumber": 4525,
"StopAreaName": "Alvik",
"TransportMode": "TRAM",
"GroupOfLine": "Tvärbanan"
},
"Deviation": {
"Text": "Tekniskt fel i skyltsystemet. För avgångstider, var god se sl.se eller tidtabell på hållplatsen.",
"Consequence": null,
"ImportanceLevel": 5
}
}
]
}
}
```

**Comment by DSorlov** [comment] 2019-11-30 23:49
Try setting the direction to 1 instead of 0

**Comment by marcus13371337** [comment] 2019-11-30 23:52
Same result:
```
unit_of_measurement: min
refresh_enabled: 'on'
attribution: Stockholms Lokaltrafik
departures: []
deviations: []
last_refresh: '2019-12-01 00:52:01'
next_departure_minutes: '-'
next_departure_time: '-'
deviation_count: 0
friendly_name: Alvik
icon: 'mdi:bus'
```

**Comment by marcus13371337** [comment] 2019-11-30 23:54
In the cached files in storage:
```
{"ri2_XXXX_9112": {"LatestUpdate": "2019-12-01T00:52:46", "DataAge": 16, "Metros": [{"GroupOfLine": "tunnelbanans gr\u00f6na linje", "DisplayTime": "2 min", "Transpor
tMode": "METRO", "LineNumber": "19", "Destination": "Hags\u00e4tra", "JourneyDirection": 2, "StopAreaName": "Alvik", "StopAreaNumber": 1201, "StopPointNumber": 1202, "StopPointDesignation": "4",
 "TimeTabledDateTime": "2019-12-01T00:56:00", "ExpectedDateTime": "2019-12-01T00:56:00", "JourneyNumber": 10763, "Deviations": null}, {"GroupOfLine": "tunnelbanans gr\u00f6na linje", "DisplayTim
e": "8 min", "TransportMode": "METRO", "LineNumber": "17", "Destination": "\u00c5keshov", "JourneyDirection": 1, "StopAreaName": "Alvik", "StopAreaNumber": 1201, "StopPointNumber": 1201, "StopPo
intDesignation": "1", "TimeTabledDateTime": "2019-12-01T01:01:30", "ExpectedDateTime": "2019-12-01T01:01:30", "JourneyNumber": 11011, "Deviations": null}, {"GroupOfLine": "tunnelbanans gr\u00f6n
a linje", "DisplayTime": "14 min", "TransportMode": "METRO", "LineNumber": "18", "Destination": "H\u00e4sselby strand", "JourneyDirection": 1, "StopAreaName": "Alvik", "StopAreaNumber": 1201, "S
topPointNumber": 1201, "StopPointDesignation": "1", "TimeTabledDateTime": "2019-12-01T01:08:00", "ExpectedDateTime": "2019-12-01T01:08:00", "JourneyNumber": 10407, "Deviations": null}, {"GroupOf
Line": "tunnelbanans gr\u00f6na linje", "DisplayTime": "22 min", "TransportMode": "METRO", "LineNumber": "18", "Destination": "Farsta strand", "JourneyDirection": 2, "StopAreaName": "Alvik", "St
opAreaNumber": 1201, "StopPointNumber": 1202, "StopPointDesignation": "4", "TimeTabledDateTime": "2019-12-01T01:16:00", "ExpectedDateTime": "2019-12-01T01:16:00", "JourneyNumber": 11147, "Deviat
ions": null}, {"GroupOfLine": "tunnelbanans gr\u00f6na linje", "DisplayTime": "01:24", "TransportMode": "METRO", "LineNumber": "19", "Destination": "\u00c5keshov", "JourneyDirection": 1, "StopAr
eaName": "Alvik", "StopAreaNumber": 1201, "StopPointNumber": 1201, "StopPointDesignation": "1", "TimeTabledDateTime": "2019-12-01T01:24:30", "ExpectedDateTime": "2019-12-01T01:24:30", "JourneyNu
mber": 10648, "Deviations": null}, {"GroupOfLine": "tunnelbanans gr\u00f6na linje", "DisplayTime": "01:26", "TransportMode": "METRO", "LineNumber": "19", "Destination": "Hags\u00e4tra", "Journey
Direction": 2, "StopAreaName": "Alvik", "StopAreaNumber": 1201, "StopPointNumber": 1202, "StopPointDesignation": "4", "TimeTabledDateTime": "2019-12-01T01:26:00", "ExpectedDateTime": "2019-12-01
T01:26:00", "JourneyNumber": 10765, "Deviations": null}, {"GroupOfLine": "tunnelbanans gr\u00f6na linje", "DisplayTime": "01:34", "TransportMode": "METRO", "LineNumber": "18", "Destination": "H\
u00e4sselby strand", "JourneyDirection": 1, "StopAreaName": "Alvik", "StopAreaNumber": 1201, "StopPointNumber": 1201, "StopPointDesignation": "1", "TimeTabledDateTime": "2019-12-01T01:34:30", "E
xpectedDateTime": "2019-12-01T01:34:30", "JourneyNumber": 10409, "Deviations": null}, {"GroupOfLine": "tunnelbanans gr\u00f6na linje", "DisplayTime": "01:46", "TransportMode": "METRO", "LineNumb
er": "18", "Destination": "Farsta strand", "JourneyDirection": 2, "StopAreaName": "Alvik", "StopAreaNumber": 1201, "StopPointNumber": 1202, "StopPointDesignation": "4", "TimeTabledDateTime": "20
19-12-01T01:46:00", "ExpectedDateTime": "2019-12-01T01:46:00", "JourneyNumber": 11148, "Deviations": null}], "Buses": [{"GroupOfLine": null, "TransportMode": "BUS", "LineNumber": "114", "Destina
tion": "Minneberg", "JourneyDirection": 1, "StopAreaName": "Alvik", "StopAreaNumber": 12025, "StopPointNumber": 12141, "StopPointDesignation": "A", "TimeTabledDateTime": "2019-12-01T01:00:00", "
ExpectedDateTime": "2019-12-01T01:00:00", "DisplayTime": "6 min", "JourneyNumber": 40267, "Deviations": null}, {"GroupOfLine": null, "TransportMode": "BUS", "LineNumber": "112", "Destination": "
Sp\u00e5nga station", "JourneyDirection": 2, "StopAreaName": "Alvik", "StopAreaNumber": 12025, "StopPointNumber": 12143, "StopPointDesignation": "C", "TimeTabledDateTime": "2019-12-01T01:19:00",
 "ExpectedDateTime": "2019-12-01T01:19:00", "DisplayTime": "25 min", "JourneyNumber": 40604, "Deviations": null}, {"GroupOfLine": null, "TransportMode": "BUS", "LineNumber": "114", "Destination"
: "Minneberg", "JourneyDirection": 1, "StopAreaName": "Alvik", "StopAreaNumber": 12025, "StopPointNumber": 12141, "StopPointDesignation": "A", "TimeTabledDateTime": "2019-12-01T01:30:00", "Expec
tedDateTime": "2019-12-01T01:30:00", "DisplayTime": "01:30", "JourneyNumber": 40270, "Deviations": null}, {"GroupOfLine": null, "TransportMode": "BUS", "LineNumber": "112", "Destination": "Sp\u0
/config/.storage/haslcache.json
```

**Comment by DSorlov** [comment] 2019-11-30 23:58
The file looks corrupted if it wasnt a copy-paste error. Try and remove the cache and refresh the data. 

If that doesnt help I will look further into it tomorrow.

**Comment by DSorlov** [comment] 2019-11-30 23:59
Any errors in the logs btw?

**Comment by marcus13371337** [comment] 2019-11-30 23:59
Didn't copy the full result due to the access keys are there etc. But that's the relevant data right? That should be able to be parsed?
This is from the log:
```
2019-12-01 00:38:41 INFO (SyncWorker_19) [custom_components.hasl.sensor] TL2 update completed for Trafikstatus...
2019-12-01 00:38:41 INFO (SyncWorker_18) [custom_components.hasl.sensor] Starting to update RI4 for Alvik...
2019-12-01 00:38:41 INFO (SyncWorker_18) [custom_components.hasl.sensor] Updated cache for Alvik...
2019-12-01 00:38:41 INFO (SyncWorker_18) [custom_components.hasl.sensor] RI4 update completed for Alvik...
2019-12-01 00:38:41 INFO (SyncWorker_18) [custom_components.hasl.sensor] Starting to update SI2 for Alvik...
2019-12-01 00:38:42 INFO (SyncWorker_18) [custom_components.hasl.sensor] Updated cache for Alvik...
2019-12-01 00:38:42 INFO (SyncWorker_18) [custom_components.hasl.sensor] SI2 update completed for Alvik...
2019-12-01 00:39:43 INFO (SyncWorker_16) [custom_components.hasl.sensor] Starting to update TL2 for Trafikstatus..
```

**Comment by marcus13371337** [comment] 2019-12-01 00:00
Thanks for your help btw!

**Comment by DSorlov** [comment] 2019-12-01 00:02
No worries at all. Well log seems to indicate that the comms are working and also the cache actually containing data. So I guess something might be failing in the parsing for the sensor output. I will need to look deeper into this tomorrow as I'm currently on my mobile from the bed and cant really do much advanced troubleshooting right now (wifey would kill me if I got up from bed). I'll update tomorrow.

**Comment by ollim89** [comment] 2020-01-04 00:38
Hi,

First of all thanks for a great component! 

I experienced this issue as well. Not sure if it's the same cause but for me the issue is when I omit the "lines" configuration variable which is optional, I was expecting to get departures for all lines.

I think the issue is here: 
https://github.com/DSorlov/hasl-platform/blob/7e2ce7e30d758cc39089dcb6bf54dddd8c3ac105/custom_components/hasl/sensor.py#L729-L730

Since lines is an empty array when omitted, it should be:
`if not self._lines or linenumber \
                                in self._lines:`

**Comment by dimmanramone** [comment] 2020-03-01 11:26
This should be fixed with the latest release

**Closed as completed by dimmanramone** 2020-03-01 11:26 UTC
Labels: question
