### ISSUE TITLE
Platform not found: sensor.hasl

### ISSUE THREAD

**Issue by Cosystick** [DSorlov/hasl-platform#41] opened 2019-08-05 16:07 UTC
**2019-08-05 17:48:43** WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hasl which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
**2019-08-05 17:48:43** ERROR (MainThread) [homeassistant.components.hassio] Platform not found: sensor.hasl

I am on Hassio 0.96.5

Config looks like this:
```
sensor:  
  - platform: mqtt
    name: "Palmen"
    state_topic: "/home/sensor/palmen"
    value_template: '{{value_json.humidity}}'
    unit_of_measurement: '%'
    device_class: humidity
  - platform: mqtt
    name: "Busken"
    state_topic: "/home/sensor/busken"
    value_template: '{{value_json.humidity}}'
    unit_of_measurement: '%'
    device_class: humidity
  - platform: hasl
    ri4key: !secret sl_realtid_apikey
    si2key: !secret sl_storning_apikey
    tl2key: !secret sl_trafik_apikey
    sensors:
    - friendly_name: Mörby
      sensor_type: departures
      siteid: 9200
      lines: ['14']
      direction: 1
    - friendly_name: Slussen
      sensor_type: departures
      siteid: 9192
      lines: ['14']
      direction: 2
    - friendly_name: Trafikstatus
      sensor_type: status
```

**Comment by maxiepax** [comment] 2019-08-08 20:45
Guess im not alone with getting the above error =)

**Comment by DSorlov** [comment] 2019-08-16 14:29
This seems to be resolved when all caches etc are emptied out. We have yet not found any code changes that have solved the error and we are not able to reproduce. I did however face the same problem myself but clearing all __pycache__, rebooting full machine solved it for mer. If anyone finds any evidence of code error it will be fixed but for now I judge this as a platform issue.

**Closed as completed** 2019-08-27 12:30 UTC
Labels: wontfix

**Comment by Cosystick** [comment] 2019-08-27 15:46
It worked after emtying the pycache and restarting the server a couple of times. Thanks and thanks for your efforts!
