### ISSUE TITLE
Problem with multiple sensors having the same departing station?

### ISSUE THREAD

**Issue by erikatl** [DSorlov/hasl-platform#25] opened 2019-05-04 17:30 UTC
I have 3 sensors from the same departing station (Helenelund). They are commuter trains southbound, commuter trains northbound and buses.

I noticed that not all of my sensors get updated when they should. Sometimes 2 out of three of the sensors are more than an hour old. So I checked the log and it is full of error messages such as this:
"Update for sensor.helenelund_pendeltag_norrut fails
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
await self.async_device_update()
File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
await self.hass.async_add_executor_job(self.update)
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.7/site-packages/homeassistant/util/init.py", line 224, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/hasl/sensor.py", line 468, in _update
departuredata = getCache(self._ri4datakey)
NameError: name 'getCache' is not defined"

**Comment by DSorlov** [comment] 2019-05-04 17:33
Confirmed bug, typo, will correct asap. Will update once done.

**Comment by erikatl** [comment] 2019-05-08 20:49
Sorry for this unnecessary comment (no, I am not in a rush to get this fixed and it *kinda* works for me), but there are quite a lot of failures...

This is what the log reports:
"Update for sensor.helenelund_pendeltag_soderut fails
22:37 custom_components/hasl/sensor.py (ERROR) - message first occured at 4 maj 2019 16:05 and shows up 8073 times
Update for sensor.helenelund_pendeltag_norrut fails
22:37 custom_components/hasl/sensor.py (ERROR) - message first occured at 4 maj 2019 16:16 and shows up 8173 times
Update for sensor.helenelund_bussar fails
22:36 custom_components/hasl/sensor.py (ERROR) - message first occured at 4 maj 2019 16:05 and shows up 7633 times"

:-)

**Comment by DSorlov** [comment] 2019-05-08 20:54
Have you tried to grab the updated code from the dev branch? Hopefully it would kill of the errors.

**Comment by erikatl** [comment] 2019-05-08 20:55
Oh, there is an update? How do I get to the dev branch? Asks the noob...

**Comment by erikatl** [comment] 2019-05-08 20:58
Found it - I think. Will give it a try.

**Comment by DSorlov** [comment] 2019-05-08 21:00
Before commiting and gathering many fixes and trying them out there is a dev branch. Hopefully this will make sure that we catch bugs like this earlier. And because of that only very urgent stuff will be pushed as separate releases.

If you look just above the code when you are in thenrepository you will se a braches tab. Click that and then select the dev branch. If you try the code from there it could be good to know if it solves your problem.

**Comment by erikatl** [comment] 2019-05-08 21:11
So I just restarted HA with the new code. Unfortunately, the problem seems to persist:
"Update for sensor.helenelund_pendeltag_norrut fails
23:08 custom_components/hasl/sensor.py (ERROR) - message first occured at 23:08 and shows up 2 times
Update for sensor.helenelund_bussar fails
23:08 custom_components/hasl/sensor.py (ERROR) - message first occured at 23:03 and shows up 12 times
Update for sensor.helenelund_pendeltag_soderut fails
23:07 custom_components/hasl/sensor.py (ERROR) - message first occured at 23:03 and shows up 10 times"
![hasl](https://user-images.githubusercontent.com/46231369/57408668-8a680380-71e6-11e9-8e0b-b631b0b57c7c.png)

**Comment by erikatl** [comment] 2019-05-08 21:14
Can I find out if the source code is actually from the dev branch? Maybe I made a mistake when downloading it?

**Comment by DSorlov** [comment] 2019-05-08 21:17
If you click the log message, could you post the details of the error?

There is no good way except comparing the code since the version number is the same still.

**Comment by erikatl** [comment] 2019-05-08 21:19
The log says:
"Wed May 08 2019 23:08:56 GMT+0200 (centraleuropeisk sommartid)
Update for sensor.helenelund_pendeltag_norrut fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/hasl/sensor.py", line 468, in _update
    departuredata = getCache(self._ri4datakey)
NameError: name 'getCache' is not defined
Anslutning tappad. Ansluter igen...
"

**Comment by DSorlov** [comment] 2019-05-08 21:24
Ok. That indicates that you did not get the right code (or that you have not restarted home assistant after updating) because that line that is referred to in the error message is actually changed.

**Comment by erikatl** [comment] 2019-05-08 21:26
OK, it's late now and I probably made a mistake. I will try again tomorrow. Anyhow I will get back.

**Comment by erikatl** [comment] 2019-05-09 09:10
The mistake I made yesterday was that I thought the dev files would be unzipped to the same folder as the main (hasl) branch. Now I restarted my HA again with the dev code and it works like a charm. No error messages in the log and all three sensors update in synch!

**Comment by DSorlov** [comment] 2019-05-09 14:33
Perfect! Thanks for the feedback.

**Comment by erikatl** [comment] 2019-05-09 20:35
Thank you for offering this fantastic service! I started out with the one you forked from. Which was good, but you took it further to - wow. :-)

**Comment by DSorlov** [comment] 2019-05-21 11:46
Fixed and released in 2.1.0

**Closed as completed by DSorlov** 2019-05-21 11:46 UTC
Labels: bug
